config/routes.rb
Rails.application.routes.draw do
  resources :pages
  devise_for :users
  resources :choices
  resources :answers
  resources :questions do
    resources :answers
  end

  root 'questions#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy 
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices, :allow_destroy => true

  # constants
  enum style: [:multiple, :bool, :freeform]

  def unanswered(current_user)
    if self.answers.where(user_id: current_user.id).length == 0
      return true
    else
      return false
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answers = @question.answers
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content, :clicks, :votes, :style, :image, :description,
                                       :choices_attributes => [:id, :name, :_destroy]
                                      )
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_choice_fields.html.erb
<div class="field nested-fields form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association "Remove", f %>
</div>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>

  <!-- this is for handling validation errors -->

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- these are the fields -->

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :style %>

    <%= f.select(:style, Question.styles.keys.map {|style| [style.titleize,style]}, {include_blank: true}, {class: 'form-control'}) %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.text_area :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>


  <script>
    $('#question_style').change(function () {
        if ($(this).val() == 'multiple') {
            $('.well').show('slow');
        } else {
            $('.well').hide('slow');
        }
    });
  </script>


  <div class='well' style='display: none;'>
    <h1>Choices</h1>
    <div id='choices'>
      <%= f.fields_for :choices do |f| %>
        <%= render 'choice_fields', :f => f %>
      <% end %>
    </div>

    <%= link_to_add_association "Add Choice", f, :choices, class: 'btn btn-default', "data-association-insertion-node" => '#choices', "data-association-insertion-method" => "append" %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div class='col-md-8'>
<div class='panel panel-default'>
<div class='panel-body'>
<h1>Listing Questions</h1>

<table class='table table-default table-striped'>
  <thead>
    <tr>
      <th>Questions</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.content %></td>
        <td>
         
         <% if current_user %>
           <% if question.unanswered(current_user) %>
             <%= link_to 'Answer', new_question_answer_path(question), class: 'btn btn-default' %>
           <% else %>
             <i class='glyphicon glyphicon-ok text-success' />
           <% end %>
         <% else %> 
           <%= link_to 'Answer', new_user_session_path, class: 'btn btn-default' %>
         <% end %>
         
         
        
          
          <%= link_to '', question, class: 'btn btn-default glyphicon glyphicon-eye-open' %>
          <% if current_user and current_user.role == 'admin' %>
            <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-default' %>
            <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user %>
  <%= link_to 'New Question', new_question_path, class: 'btn btn-default' %>
<% end %>

</div>
</div>

</div>

<% if !current_user %>
<div class='col-md-4'>
  <%= render "devise/sessions/form" %>
</div>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @question.content %>
</h1>

<% if @question.style == 'multiple' %>
  <% @question.choices.each_with_index do |choice, i| %>
    <h2><%= i+1 %>. <%= choice.name %></h2>
  <% end %>
<% end %>


<div class='well'>
  <h1><%= @answers.length %> Answers</h1>

  <table class='table table-default table-striped'>
    <tr>
      <th>Answer</th>
      <th>Created At</th>
    </tr>

    <% @answers.each do |answer| %>
      <tr>
        <td>
          <% if @question.style == 'multiple' %>
            <%= answer.choice.name %>
          <% end %>
          <% if @question.style == 'bool' %>
            <% if answer.yes_no == true %>
              Yes
            <% elsif answer.yes_no == false %>
              No
            <% end %>
          <% end %>
          <% if @question.style == 'freeform' %>
            <%= answer.content %>
          <% end %>
        </td>
        <td><%= answer.created_at %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to 'Back', questions_path %>